name: JasmineHall
favicon: null
layout_spectrum: 0.9683825301472098
typography_spectrum: 0.25630878028459847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6742677865549922
  lightness: 0.7398596093989909
  saturation: 0.520129653159529
  rhythmicContrast: 0.47495502536185086
purpose: []
